### ISSUE TITLE
Configure Script Needs To Detect Compiler Support For wstring_convert

### ISSUE THREAD

**Issue by wbraswell** [jpcre2/jpcre2#18]
@neurobin 
The `configure` script successfully detects and gracefully fails if the compiler does not support C++11 features, however `configure` does NOT gracefully detect if the compiler supports the `wstring_convert` class template.  You can see an example of the un-graceful compiler error below, which is difficult to decipher and diagnose:

`
CXX test_match2-test_match2.o
In file included from test_match2.cpp:9:0:
jpcre2.hpp:1233:31: error: wstring_convert in namespace std does not name a template type
struct ConvUTF { typedef std::wstring_convert<Codecvt<Char_T, char, std::mbstate_t>, Char_T> Converter; };
...
Makefile:1065: recipe for target 'test_match2-test_match2.o' failed
`

http://www.cpantesters.org/cpan/report/e8448fbc-6821-11e7-8b43-cc7d71ffb3b6

What we need is simply a nice graceful failure message like we already have for C++11:

`configure: error: *** A compiler with support for C++11 language features is required.`

Also, please be aware that `wstring_convert` is marked as "Deprecated in C++17" (cppreference.com), although there does not seem to be any movement to actually remove support because there is no replacement (reddit)?

http://en.cppreference.com/w/cpp/locale/wstring_convert

https://www.reddit.com/r/cpp_questions/comments/5yo0el/stdwstring_convert_and_stdcodecvt_utf8_deprecated/

**Comment by neurobin** [comment]
Thanks for reporting and providing me with all the information.

The configure script is fixed now.

I have opened an issue #19  as a reminder to the deprecation status of `std::wstring_convert`.

Though it is possible to remove the use of UTF conversion from the library altogether without breaking any basic functionality, I don't plan on doing so right now because it provides a handy way to convert between UTF-8<>UTF16 and UTF-8<>UTF-32 and also the ability to provide useful error messages combining integer error values/offsets (`int` to `std::u16string` and `std::u32string`). If you have any suggestion/opinion on this, let me know.

Regards,
Jahid.

**Comment by wbraswell** [comment]
@neurobin 
Thanks for the quick fix!
I have disabled C++11 features in Alien::JPCRE2 for now, because we are encountering a large number of systems with old compilers.  This new configure warning will come in handy when more people have C++11 compliant compilers.

**Comment by neurobin** [comment]
@wbraswell 
As `wstring_convert` is removed, you can use c++11 in older compilers. I have tested with as low as `g++-4.8` which is pretty much ancient.
